/** Shared Geneva Care Logs branding line for detail views and PDFs. */
export function genevaCareLogsGeneratedLine() {
    const dateStr = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
    });
    return `Generated by Geneva Care Logs system on ${dateStr}.`;
}
