<?php

namespace App\Support;

use Illuminate\Support\Facades\File;
use Illuminate\Support\HtmlString;

class ViteLegacy
{
    /**
     * Prepend the modern polyfill entry when the production manifest includes it.
     */
    public static function entries(array $entries): array
    {
        $manifest = self::manifest();
        if (! $manifest || self::isHot()) {
            return $entries;
        }

        if (! empty($manifest['vite/legacy-polyfills']['file'])) {
            array_unshift($entries, 'vite/legacy-polyfills');
        }

        return $entries;
    }

    /**
     * Emit nomodule scripts generated by @vitejs/plugin-legacy.
     */
    public static function scripts(string $entry): HtmlString
    {
        if (self::isHot()) {
            return new HtmlString('');
        }

        $manifest = self::manifest();
        if (! $manifest) {
            return new HtmlString('');
        }

        $legacyEntry = self::legacyFileForEntry($manifest, $entry);
        if (! $legacyEntry) {
            return new HtmlString('');
        }

        $polyfill = $manifest['vite/legacy-polyfills-legacy']['file'] ?? null;

        $safariFix = '!function(){var e=document,t=e.createElement("script");if(!("noModule"in t)&&"onbeforeload"in t){var n=!1;e.addEventListener("beforeload",(function(e){if(e.target===t)n=!0;else if(!e.target.hasAttribute("nomodule")||!n)return;e.preventDefault()}),!0),t.type="module",t.src=".",e.head.appendChild(t),t.remove()}}();';

        $html = '<script nomodule>'.$safariFix.'</script>'."\n";
        if ($polyfill) {
            $html .= '<script nomodule crossorigin id="vite-legacy-polyfill" src="'.e(asset('build/'.$polyfill)).'"></script>'."\n";
        }
        $html .= '<script nomodule crossorigin id="vite-legacy-entry" data-src="'.e(asset('build/'.$legacyEntry)).'">System.import(document.getElementById("vite-legacy-entry").getAttribute("data-src"))</script>';

        return new HtmlString($html);
    }

    protected static function legacyFileForEntry(array $manifest, string $entry): ?string
    {
        $directory = pathinfo($entry, PATHINFO_DIRNAME);
        $filename = pathinfo($entry, PATHINFO_FILENAME);
        $extension = pathinfo($entry, PATHINFO_EXTENSION);

        $candidates = [
            "{$directory}/{$filename}-legacy.{$extension}",
            "{$directory}/{$filename}-legacy.js",
            "{$entry}-legacy",
        ];

        foreach ($candidates as $key) {
            if (! empty($manifest[$key]['file'])) {
                return $manifest[$key]['file'];
            }
        }

        foreach ($manifest as $key => $chunk) {
            if (empty($chunk['file']) || ! is_string($key)) {
                continue;
            }
            if (
                str_contains($key, $filename)
                && str_contains($key, 'legacy')
                && ! str_contains($key, 'polyfill')
            ) {
                return $chunk['file'];
            }
        }

        return null;
    }

    protected static function isHot(): bool
    {
        return is_file(public_path('hot'));
    }

    protected static function manifest(): ?array
    {
        $manifestPath = public_path('build/manifest.json');
        if (! is_file($manifestPath)) {
            return null;
        }

        $manifest = json_decode(File::get($manifestPath), true);

        return is_array($manifest) ? $manifest : null;
    }
}
